### ISSUE TITLE
Can't get response from URL

### ISSUE THREAD

**Issue by zn3x** [TheSuunny/Yove.Http#2]
I'am trying a simple code like this one:

```
using System;
using System.Threading.Tasks;
using Yove.Http;
using Yove.Http.Proxy;

public class Program
{
    public static void Main()
    {
        Task<string> result = MmAsync();

        Console.WriteLine(result.Result);
    }

    public static async Task<string> MmAsync()
    {
        HttpClient Client = new HttpClient();
        HttpResponse Response = await Client.Get("http://example.com/");
        string Body = Response.Body;
        return Body;
    }
}
```

but I keep getting an error like:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Failed receive data from - http://example.com/) ---> System.Exception: Failed receive data from - http://example.com/
   at Yove.Http.HttpClient.Raw(HttpMethod Method, String URL, HttpContent Content)
   at Yove.Http.HttpClient.ReconnectFail()
   at Yove.Http.HttpClient.Raw(HttpMethod Method, String URL, HttpContent Content)
   at Yove.Http.HttpClient.ReconnectFail()
   at Yove.Http.HttpClient.Raw(HttpMethod Method, String URL, HttpContent Content)
   at Yove.Http.HttpClient.ReconnectFail()
   at Yove.Http.HttpClient.Raw(HttpMethod Method, String URL, HttpContent Content)
   at Yove.Http.HttpClient.Get(String URL)
   at Program.MmAsync() in C:\Users\home\source\repos\test\Program.cs:line 19
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Program.Main() in C:\Users\home\source\repos\test\Program.cs:line 13
```

Did I forgot something?

**Comment by TheSuunny** [comment]
![DeepinScreenshot_dde-desktop_20190515103604](https://user-images.githubusercontent.com/44042783/57757045-3df85880-76fd-11e9-95ba-a533bb898b6c.png)

![DeepinScreenshot_dde-desktop_20190515103752](https://user-images.githubusercontent.com/44042783/57757146-76983200-76fd-11e9-944a-6d4d54853fe3.png)

Hello, please check again, you may have had problems with the connection

**Comment by zn3x** [comment]
Any other idea of what causing this issue? I've tried to use a simple socket to get data from host and it seems to work fine (to check if It is an issue in my connection)

**Comment by TheSuunny** [comment]
So far I cannot even guess what the problem is, if the site is available, so it happens with all sites? Or just example.com?

Please try making a request here - https://api6.ipify.org/?format=json

**Comment by zn3x** [comment]
That's not the issue, I've already tried multiple urls but the same error is thrown

After reading the httpclient class in the Raw obj, it seems that the data is succefully sent but it fails to receive from host

**Comment by TheSuunny** [comment]
Hmm, very strange, little later I will make a more detailed version where can examine the normal StackTrace, and what exactly caused this error, do you have a discord?

**Comment by zn3x** [comment]
Wait, Does The Raw obj call an external package to do some kind of enc/decrypt to the response?

**Comment by TheSuunny** [comment]
There is a package 'System.Text.Encoding.CodePages', nuget should pull it himself

**Comment by zn3x** [comment]
Ok, it seems that this is the issue, it seems that I manually added `Yove.Http` to project from a package of another one, and because of that and it seems that even if no error is raised,  `System.Text.Encoding.CodePages` is not loaded and that what causes the error when calling an obj from it.

Thanks for help!

**Comment by TheSuunny** [comment]
Try installing via nuget

Windows Visual Studio - Tools > Library package manager > Manage Nuget Packages > Search `Yove.Http`

 Linux Terminal - `dotnet add package Yove.Http`

**Comment by TheSuunny** [comment]
Always happy to help :)

A bit later I will add a normal StackTrace for a better understanding of the error.
